services:
  - type: web
    name: revplay-api-gateway
    env: java
    plan: free
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/api-gateway-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 9080
    healthCheckPath: /actuator/health
