# 🚀 RevPlay AWS S3 Deployment

name: Build Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: 🚀 Build Frontend
    
    defaults:
      run:
        working-directory: revplay-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: revplay-frontend/package-lock.json

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular App
        run: ng build --configuration production

      - name: Verify build output
        run: ls -R dist
